### ISSUE TITLE
Move command issues to commands repo

### ISSUE THREAD

**Issue by zoli** [limetext/backend#112]
They should go here https://github.com/limetext/commands.

**Comment by thewhitetulip** [comment]
@zoli 
I had started to write a python plugin to migrate issues, but found this instead https://github.com/IQAndreas/github-issues-import

I'd have done it, but I don't have write access. I migrated a few issues manually though.

**Comment by zoli** [comment]
OK, I will look at it.

**Comment by zoli** [comment]
@thewhitetulip Thanks, I moved all issues with the help of the script you mentioned.

**Comment by thewhitetulip** [comment]
Wow, this is what @ricochet1k was talking about, it looks like a facebook feed :D

so many notifications
