### ISSUE TITLE
Race condition in TestClipboard

### ISSUE THREAD

**Issue by mewmew** [limetext/backend#70]
Notice that expected and got have the same value:

```
--- FAIL: TestClipboard-2 (0.12s)
    editor_test.go:180: Expected "test0" to be on the clipboard, but got "test0"
```

Extract from `editor_test.go:180`:

``` go
    s := "test0"

    editor.SetClipboard(s)

    if editor.GetClipboard() != s {
        t.Errorf("Expected %q to be on the clipboard, but got %q", s, editor.GetClipboard())
    }
```

The returned value of the first invocation of `editor.GetClipboard()` is not "test0", whereas the returned value of the second invocation of `editor.GetClipboard()` is "test0", thus indicating a race condition.

One way of fixing this issue would be to store the returned value from `editor.GetClipboard()`, e.g.:

``` go
    want := "test0"

    editor.SetClipboard(want)

    if got := editor.GetClipboard(); got != want {
        t.Errorf("Expected %q to be on the clipboard, but got %q", want, got)
    }
```
##

**Comment by mewmew** [comment]
Forgot to mention, this happened while using the following revision of the backend: limetext/lime-backend@16b6a1a89f3982cbead6995febb68dbab40b7a7e.

```
$ go version
go version devel +a788c91 Thu Jun 11 16:30:56 2015 +0000 linux/amd64
```

**Comment by erbridge** [comment]
Well spotted. Could you open a PR to fix that, please?

**Comment by mewmew** [comment]
> Well spotted. Could you open a PR to fix that, please?

Will do. Should arrive in a couple of days as we are currently celebrating midsummer in Sweden :)

**Comment by quarnster** [comment]
> The returned value of the first invocation of editor.GetClipboard() is not "test0", whereas the returned value of the second invocation of editor.GetClipboard() is "test0", thus indicating a race condition.

So in other words SetClipboard is an asynchronous operation? Looking at [github.com/atotto/clipboard](https://github.com/atotto/clipboard)'s source code it isn't obvious. @mewmew, You're on Linux, right? Do you know whether `xsel` or `xclip` gets used and does `go test github.com/atotto/clipboard` fail randomly for you as well?

**Comment by mewmew** [comment]
> So in other words SetClipboard is an asynchronous operation?

It would seem so. Otherwise I cannot explain the behaviour, as the output error string clearly contains "test0" for both `got` and `want`.

> You're on Linux, right?

I am :)
```
[~]$ uname -a
Linux x61s 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux
```

> Do you know whether `xsel` or `xclip` gets used

I don't have the `xsel` command. Does the backend invoke `xclip`?

> does `go test github.com/atotto/clipboard` fail randomly for you as well?

After 10 consecutive runs I always get the same result, PASS:

```
[~]$ go test -v github.com/atotto/clipboard
=== RUN   TestCopyAndPaste
--- PASS: TestCopyAndPaste (0.01s)
=== RUN   TestMultiCopyAndPaste
--- PASS: TestMultiCopyAndPaste (0.02s)
=== RUN   Example
--- PASS: Example (0.01s)
PASS
ok  	github.com/atotto/clipboard	0.050s
```

**Comment by quarnster** [comment]
> I don't have the xsel command. Does the backend invoke xclip?

It uses `github.com/atotto/clipboard` which uses xsel or xclip (whichever is installed) if I read the code correctly.

> After 10 consecutive runs I always get the same result, PASS:

How consistent is the failure in lime-backend? I would have expected a similar failure rate for atotto/clipboard as it's what is used underneath lime-backend. Does it ever fail if you do:

`for i in {1..1000}; do go test github.com/atotto/clipboard; done`

?

**Comment by mewmew** [comment]
> `for i in {1..1000}; do go test github.com/atotto/clipboard; done`

The test does indeed fail when executed multiple times in a row. On average 1% of the time, or 10 times during roughly 900 runs.

Some examples of failures are provided below:

```
ok  	github.com/atotto/clipboard	0.117s
--- FAIL: TestMultiCopyAndPaste (0.06s)
	clipboard_test.go:57: want Weird UTF-8: 💩☃, got French: éèêëàùœç
FAIL
FAIL	github.com/atotto/clipboard	0.132s
ok  	github.com/atotto/clipboard	0.114s
ok  	github.com/atotto/clipboard	0.094s
--- FAIL: Example (0.02s)
got:
Weird UTF-8: 💩☃
want:
日本語
FAIL
FAIL	github.com/atotto/clipboard	0.107s
ok  	github.com/atotto/clipboard	0.139s
ok  	github.com/atotto/clipboard	0.061s
--- FAIL: TestMultiCopyAndPaste (0.04s)
	clipboard_test.go:44: want French: éèêëàùœç, got 日本語
FAIL
FAIL	github.com/atotto/clipboard	0.064s
ok  	github.com/atotto/clipboard	0.083s
```

I think it is strange that `clipboard.WriteAll` is asynchronous since the [Linux implementation](https://github.com/atotto/clipboard/blob/dfde2702d61cc95071f9def0fe9fc47d43136d6d/clipboard_linux.go#L82) always invokes `copyCmd.Wait()` in the non-error case.

**Comment by mewmew** [comment]
To minimize the risk of other issues causing this, I've removed all cached packages (e.g. `$GOPATH/pkg/*`) and recompiled and re-ran the tests using Go 1.4. The above failures were spotted when running the Go 1.4 build.

```
$ go version
go version go1.4.1 linux/amd64
```

**Comment by quarnster** [comment]
>we are currently celebrating midsummer in Sweden :)

Related/offtopic: https://www.youtube.com/watch?v=0k8Nu2YJMzY

**Comment by ch1bo** [comment]
Hey, I checked out this issue and only encountered FAIL when testing the backend lib package with all subpackages (other test cases omitted):
```
go test ./... -v 
[...]
=== RUN TestClipboard-4
got clipboard:
clipoard

set clipboard:
test0
got clipboard:
test0
set clipboard:
test1
got clipboard:
test0
set clipboard:
clipoard

--- FAIL: TestClipboard-4 (0.03s)
	editor_test.go:188: Expected "test1" to be on the clipboard, but got "test0"
[...]
FAIL
FAIL	github.com/limetext/lime-backend/lib	8.178s
[...]
```
When only running tests of the lib package itself I get PASS (other test cases omitted):
```
$ go test . -v
[...]
=== RUN TestClipboard-4
got clipboard:
clipoard

set clipboard:
test0
got clipboard:
test0
set clipboard:
test1
got clipboard:
test1
set clipboard:
clipoard

--- PASS: TestClipboard-4 (0.02s)
[...]
```

Note my added printlns:
```
diff --git a/lib/editor.go b/lib/editor.go
index 634c538..d5fd891 100644
--- a/lib/editor.go
+++ b/lib/editor.go
@@ -408,6 +408,8 @@ func (e *Editor) SetClipboard(n string) {
        if err := e.clipboardSetter(n); err != nil {
                log.Error("Could not set clipboard: %v", err)
        }
+       println("set clipboard:")
+       println(n)
 
        // Keep a local copy in case the system clipboard isn't working
        e.clipboard = n
@@ -415,11 +417,14 @@ func (e *Editor) SetClipboard(n string) {
 
 func (e *Editor) GetClipboard() string {
        if n, err := e.clipboardGetter(); err == nil {
+               println("got clipboard:")
+               println(n)
                return n
        } else {
+               println("could not get clipboard:")
+               println(err.Error())
                log.Error("Could not get clipboard: %v", err)
        }
-
        return e.clipboard
 }
```

BTW: I could not get any FAILs on the clipboard package of atotto in 1000+ runs.

**Comment by mewmew** [comment]
Close the issue for now as it has remained inactive for more than 6 months.

Anyone with more insight into the current status may re-open the issue or add a comment about the current progress.
