### ISSUE TITLE
Sublime tests fail on go 1.6

### ISSUE THREAD

**Issue by erbridge** [limetext/backend#87]
`panic: runtime error: cgo result has Go pointer` in `TestSublime` (see e.g. https://travis-ci.org/limetext/lime-backend/jobs/118307558). The issue lies in `gopy`.

**Comment by zoli** [comment]
https://travis-ci.org/limetext/lime-backend/jobs/118525443

**Comment by sunxfancy** [comment]
It thrown this error after loading Diff plugin in my platform, ubuntu 16.04, go 1.6

**Comment by jacobrosenthal** [comment]
I think the projects still on Go 1.5x

**Comment by erbridge** [comment]
Yes. We still have some pointer issues preventing it from working with go1.6.

**Comment by erbridge** [comment]
Moved to limetext/sublime#3.
