### ISSUE TITLE
Restructuring backend repo

### ISSUE THREAD

**Issue by zoli** [limetext/backend#94]
I think we should move out util, sublime and commands(maybe also watch?) packages to separate repo. These packages are not imported in backend package and are not directly related they just use backend package exported api and should be optional for frontends.
Also IMO one of limetext design goals is backend/frontend separation, this could be more clear by making the frontends just import `github.com/limetext/lime-backend/lib`(no sub packages) and importing other optional packages like `github.com/limetext/sublime` or `github.com/limetext/commands`.

/cc @erbridge

**Comment by erbridge** [comment]
We have talked about this idea in the past, I believe, and I am all for it. If packages are sufficiently decoupled, it makes sense to pull them out into their own repos.

**Comment by zoli** [comment]
Moved out sublime util and commands to separate repo. will keep this issue open for now I'm thinking on moving out loaders and watch package to separate repo to also some thinking on lime-backend structure

**Comment by erbridge** [comment]
Let's make sure the test suites are run on the new repos, too. FYI, this is why the backend is in a `lib` subfolder, so the `tasks` can be brought in without being imported.

**Comment by zoli** [comment]
Just to mention we had some discussions here https://github.com/limetext/lime/issues/546 about this some issues are resolved but still we have the tasks folder problem. 
We don't need `tasks/local/build/gen_python_api.go` anymore in this repo we should move it to https://github.com/limetext/sublime then running `go test github.com/limetext/lime-backend/...` won't raise any error.
